### ISSUE TITLE
Shell script doesn't run on Windows

### ISSUE THREAD

**Issue by santiagoalmeidabolannos** [dgurkaynak/stalk-opentracing-js#2]
this script https://github.com/dgurkaynak/stalk-opentracing-js/blob/master/scripts/symlink.sh to create a Symbolic Link is not supported by Windows. Any nice solution please?

**Comment by asciidisco** [comment]
Not affiliated with this project, but I'd suggest to drop the shell script for an OS independent version backed by https://www.npmjs.com/package/symlink-or-copy

**Comment by dgurkaynak** [comment]
Sorry for the late response, somehow I wasn't following my own project. 

That symlink script is legacy actually. I've just removed that post-install script and published `0.0.5` version. It shouldn't be a problem any more on windows.
